### ISSUE TITLE
Add discussion or remove _extras/discuss.md

### ISSUE THREAD

**Issue by ashander** [datacarpentry/sql-ecology-lesson#141]

**Comment by orchid00** [comment]
@tracykteal is this needed?

**Comment by ashander** [comment]
I've asked about this and #142 in the gitter lobby, but won't get to it till tomorrow, likely

**Comment by tracykteal** [comment]
I looked at how 'Discussion' was being used in the SWC lessons. These are some examples

http://swcarpentry.github.io/python-novice-inflammation/discuss/
http://swcarpentry.github.io/shell-novice/discuss/
http://swcarpentry.github.io/git-novice/discuss/

None of the Data Carpentry lessons have a Discussion section right now, because it wasn't material developed under the old template. So, maybe the best thing to do is to leave it as it is as a placeholder document. Then for the next release we can figure out how we want to use the Discussion pages in Data Carpentry lessons.

**Comment by ashander** [comment]
OK, I've deleted the other, unused extras/figures in #160 but will leave this one. I guess this issue can be left as a flag for the next release. (But the labels should prob be changed to indicate that.)

**Comment by tracykteal** [comment]
Added the 'after lesson release' tag to come back to this
