### ISSUE TITLE
missing semi colons

### ISSUE THREAD

**Issue by njamescouk** [datacarpentry/sql-ecology-lesson#144]
bit of a nit pick - https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/_episodes/02-sql-aggregation.md has multiple SELECT statements with missing semi colons. copy paste from html into sqlite manager works ok, reading and typing will fail.

see https://gist.github.com/njamescouk/b7bf308bf2f0af3703c674f3a152526f for rudimentary tool

**Comment by orchid00** [comment]
Hi Nick, small changes and typos should go as PR. Issues should be opened when there is need for discussion before the change. Thanks for the suggestions.

**Comment by tpoisot** [comment]
Closing -- reopen as PR.

**Comment by ashander** [comment]
@tpoisot you should reopen until there is a PR. And this policy needed better coordination with @tracykteal / @ErinBecker --- during the issue bonanza we were told 'Open Issues, not PRs'

**Comment by ErinBecker** [comment]
@orchid00 @tpoisot @ashander @tracykteal 

Thanks for the discussion here folks. @ashander is correct that for the Issue Bonanza we were focusing on submitting all change requests as issues, rather than PRs. Tracy and I have it on our calendar to go through the lessons and clean up many of the "minor" issues (such as the typos referenced in this issue) so that this doesn't take up maintainer time. 

During the upcoming Bug BBQ we'll be focusing community effort on the more substantial issues that will required discussion or significant formatting work.

**Comment by njamescouk** [comment]
@orchid00 @tpoisot @ashander @tracykteal @ErinBecker 
Apologies for breach of protocol, I wasn't aware of the intricacies of the situation. Can understand  that apparent random bod hammering on a repo would be, at the least, disconcerting.

Perhaps a better way forward would be for bug bonanza people to fork the repo in question, invite people to submit issues then the  bug bbq instigators could roll them up into PR(s) for submission to maintainers? Downsides include yet another fork, but the clone could be deleted once PRs dealt with?  Another option would be to mark issues created via bug bbq to be marked as such, or link to bug bbq put in body of issue?

atb Nick J

**Comment by orchid00** [comment]
@ErinBecker @tpoisot @tracykteal I still think the best way to handle typos and small changes is to open them as PR's instead of issues. Those are easy changes that make a difference in how clear is the content.

**Comment by njamescouk** [comment]
Whilst my suggestion *is* an extra loop, it would avoid hammering the main repo, in fact the maintainers would be in blissful ignorance until such time as properly formed PR(s) turned up.

**Comment by tracykteal** [comment]
Thanks, yes, this was a special case to make sure we were capturing issues that needed to be resolved. Since this was the first Issue Bonanza we might not have gotten the workflow quite right! Thank you for the feedback, and we'll plan on how to do this more cleanly for next time. 

For now, @orchid00 and @tpoisot  it would be great if we could leave these issues open and @ErinBecker and I will go through and submit the small PRs to resolve them.

**Comment by tracykteal** [comment]
Closed by https://github.com/datacarpentry/sql-ecology-lesson/issues/150
