### ISSUE TITLE
add solutions for exercises/challenges

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/sql-ecology-lesson#179]
Most of the challenges for the SQL lessons are missing solutions. It would be great to include those similar to how they're done in OpenRefine and Spreadsheets lessons.

<table>
<tr><th>Episode</th><th>PR</th><tr>
<tr><td>01 Databases using SQL</td><td>#187, #204</td></tr>
<tr><td>02 Basic Queries</td><td>#204</td></tr>
<tr><td>03 SQL Aggregation and aliases</td><td>#204</td></tr>
<tr><td>04 Joins</td><td>#204</td></tr>
</table>

**Comment by kariljordan** [comment]
I wanted to +1 @ErinBecker because I just went through the lesson on my own to prepare to teach it in June and wanted to confirm that my queries are correct for the challenge questions. @orchid00 @tpoisot are there any plans to add the solutions to the challenge questions?

**Comment by orchid00** [comment]
Working now with @nek555 on PR #187 which will lead to many small updates.

**Comment by orchid00** [comment]
This is still pending. @kariljordan @ErinBecker To clarify expectations I won't add any solutions to challenges. I would instead welcome any contributions from people who are preparing to teach this lesson.

**Comment by kariljordan** [comment]
Will you send out a "call for contributions"?

**Comment by orchid00** [comment]
Hi Kari, that is not my plan, but you are welcome to do the call.

**Comment by kariljordan** [comment]
Hopefully someone in the SQL loving community can contribute, or maybe @tpoisot? I'm not skilled in SQL so I'm not able to help with this. Good luck!

**Comment by sheraaron** [comment]
Contribution by Ioanna Lampaki

## SQL for ecology: Solutions to challenges

This document lists all challenges and their solutions in the right order of appearance as in http://www.datacarpentry.org/sql-ecology-lesson/ . It addresses Issue #179 (https://github.com/datacarpentry/sql-ecology-lesson/issues/179) and also includes additional or slightly different challenges of older versions as provided in https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/sql-solutions.md. Contributed solutions are marked with **(ADDED)**.


## Basic Queries

**EXERCISE**

Write a query that returns the year, month, day, species ID and weight (in mg).

**SOLUTION**

	     SELECT day, month, year, species_id, weight * 1000
	     FROM surveys;

<br>

**EXERCISE**

Write a query that returns the day, month, year, species ID, and weight (in kg)
for individuals caught on Plot 1 that weigh more than 75 g.

**SOLUTION 1**

	    SELECT day, month, year, species_id, weight / 1000.0
	    FROM surveys
	    WHERE (plot_id = 1 AND weight > 75);


**SOLUTION 2 (assumes knowledge of joins which are taught in a later chapter)**

	   SELECT
		surveys.day,
		surveys.month,
		surveys.year,
		species.species_id,
		surveys.weight / 1000
	   FROM surveys
	   JOIN species ON surveys.species_id = species.species_id
	   WHERE surveys.weight > 75
	   AND surveys.plot_id = 1;

<br>

**EXERCISE**

Write a query that returns day, month, year, species ID for individuals caught
in January, May and July.

 **SOLUTION**

	   SELECT day, month, year, species_id
	   FROM surveys
	   WHERE month IN (1, 5, 7);

<br>

**EXERCISE**

Write a query that returns year, species ID, and weight in kg from the surveys table, sorted with the largest weights at the top.

**SOLUTION**

	   SELECT year, species_id, weight / 1000
	   FROM surveys 
	   ORDER BY weight DESC;

<br>

**EXERCISE**

Let’s try to combine what we’ve learned so far in a single query. Using the surveys table write a query to display the three date fields, species ID, and weight in kilograms (rounded to two decimal places), for individuals captured in 1999, ordered alphabetically by the species ID.

**SOLUTION**

	   SELECT year, month, day, species_id, ROUND(weight / 1000, 2)
	   FROM surveys
	   WHERE year = 1999
	   ORDER BY species_id;
	

## SQL Aggregation and aliases


**EXERCISE**

Write a query that returns: total weight, average weight, and the min 
and max weights for all animals caught over the duration of the survey. 

Can you modify it so that it outputs these values only for weights between 5 and 10 ?

**SOLUTION (ADDED)**

        SELECT SUM(weight), AVG(weight), MIN(weight), MAX(weight) 
        FROM surveys
        SELECT SUM(weight), AVG(weight), MIN(weight), MAX(weight) 
        FROM surveys 
        WHERE (weight > 5 AND weight < 10)
	
<br>
	
**EXERCISE (ADDED)**

Write queries that return:
1. How many individuals were counted in each year
      o in total 
      o per each species

2. Average weight of each species in each year.

Can you modify the above queries combining them into one?

**SOLUTION**
1
 
        SELECT year, COUNT(*)
        FROM surveys
        GROUP BY year;

        SELECT year, species_id,COUNT(*)
        FROM surveys
        GROUP BY year,species_id;
        
2

        SELECT year, species_id, ROUND(AVG(weight), 2)
        FROM surveys
        GROUP BY year, species_id;
	
        SELECT year, species_id,COUNT(*), ROUND(AVG(weight), 2)
        FROM surveys
        GROUP BY year, species_id;

<br>

**EXERCISE**

Write a query that returns, from the species table, the number of genus 
in each taxa, only for the taxa with more than 10 genus.

**SOLUTION (ADDED)**

       SELECT  taxa, genus, COUNT(*) as n
       FROM species
       GROUP BY taxa
       HAVING n > 10


**Additional or slightly different exercises from older versions of this chapter.**

**EXERCISE**

Write queries that return:

1. How many individuals were counted in each year.

2. Average weight of each species in each year.

**SOLUTION**
 1
          
         SELECT year, COUNT(*)
	     FROM surveys
	     GROUP BY year;
   
2
        
         SELECT year, species_id, ROUND(AVG(weight), 
         FROM surveys
	     GROUP BY year, species_id;

<br>

**EXERCISE**

Write a query that returns the number of each species caught in each year
sorted from most often caught species to the least occurring ones within each
year starting from the most recent records.

**SOLUTION**

	   SELECT year, species_id, COUNT(*)
	   FROM surveys
	   GROUP BY year, species_id
	   ORDER BY year DESC, COUNT(*) DESC;



 ## Joins


**EXERCISE**

Write a query that returns the genus, the species, and the weight of every
individual captured at the site.

**SOLUTION**

        SELECT species.genus, species.species_id, surveys.weight
	    FROM surveys
	    JOIN species 
        ON surveys.species_id = species.species_id;

<br>

**EXERCISE**

Re-write the original query to keep all the entries present in the surveys table. How many records are returned by this query?

**SOLUTION (ADDED)**

       SELECT * FROM surveys 
       LEFT JOIN species 
       USING (species_id)

<br>

**EXERCISE**   

Count the number of records in the surveys table that have a NULL value 
in the species_id column.

**SOLUTION (ADDED)**

       SELECT COUNT(*) 
       FROM surveys 
       WHERE species_id IS NULL

<br>

**EXERCISE**

 Write a query that returns the number of genus of the animals caught 
 in each plot in descending order.
 
 **SOLUTION**
 
        SELECT surveys.plot_id, species.genus, COUNT(*)
        FROM surveys
        JOIN species 
        ON surveys.species_id = species.species_id
        GROUP BY species.genus, surveys.plot_id
        ORDER BY surveys.plot_id DESC
	
<br>	

**EXERCISE**

Write a query that finds the average weight of each rodent species 
(i.e., only include species with Rodent in the taxa field).

 **SOLUTION (ADDED)**
 
        SELECT AVG(surveys.weight) 
        FROM surveys 
        JOIN species 
        ON surveys.species_id = species.species_id 
        WHERE species.taxa='Rodent';

<br>

**EXERCISE**

Write a query that returns 30 instead of NULL for values in the hindfoot_length column.

 **SOLUTION (ADDED)**
 
        SELECT hindfoot_length, IFNULL(hindfoot_length,30) 
        FROM surveys;
	
<br>
	
**EXERCISE**

Write a query that calculates the average hind-foot length of each species, 
assuming that unknown lengths are 30 (as above).

**SOLUTION (ADDED)**

        SELECT species_id, avg(IFNULL(hindfoot_length,30)) 
        FROM surveys
        GROUP BY species_id;
	
<br>

**EXERCISE**

Write a query that returns the number of genus of the animals caught in each plot, 
using IFNULL to assume that unknown species are all of the genus 'Rodent'.

**SOLUTION (ADDED)**

        SELECT genus, plot_id, IFNULL(genus, 'Rodent') AS genus2, COUNT(*)
        FROM surveys LEFT JOIN species 
        ON surveys.species_id=species.species_id
        GROUP BY plot_id, genus2

<br>

**EXERCISE**

Write a query that returns genus names, sorted from longest genus name down to shortest.

**SOLUTION (ADDED)**

       SELECT genus
       FROM species 
       ORDER BY LENGTH(genus) DESC

**Comment by remram44** [comment]
Thanks @sheraaron! I did my best to turn this into PR #204, unfortunately I couldn't find some of those exercises in the lesson.

**Comment by kariljordan** [comment]
These are awesome contributions @remram44!

**Comment by kariljordan** [comment]
@ErinBecker is there a specific SQL maintainer that needs to be pinged for this?

**Comment by ErinBecker** [comment]
@kariljordan - @remram44 is the new Maintainer! :-)

**Comment by remram44** [comment]
As I understand it @tpoisot is my co-maintainer, I'm sure he will get to this in due time (I can't actually merge).

**Comment by ErinBecker** [comment]
@remram44 - you should have merge access. I'll double check the settings for the repo.

**Comment by pmarchand1** [comment]
The optional challenge 5 in episode 03: "What is the percentage of each species in each taxa?" also seems to require complex sub-queries, so I would suggest removing it (I will do so in my pull request for this issue).

**Comment by pmarchand1** [comment]
I haven't looked into integrating the solutions from #187. The main difference is that they include a few solution notes, not sure what is the Data Carpentry standard for those.

**Comment by ChristinaLK** [comment]
all exercises appear to have solutions.
