### ISSUE TITLE
Note differences between different database management systems

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/sql-ecology-lesson#277]
On the [SQL introduction](https://datacarpentry.org/sql-ecology-lesson/00-sql-introduction/index.html) page, we note:

> There are a number of different database management systems for working with relational data. We’re going to use SQLite today, but basically everything we teach you will apply to the other database systems as well (e.g. MySQL, PostgreSQL, MS Access, MS SQL Server, Oracle Database and Filemaker Pro). The only things that will differ are the details of exactly how to import and export data and the details of data types.

This is misleading, as there are many other differences between different database systems.  For example, SQLite does not do every kind of `join` (inner/outer/full/left/right).   Acceptable syntax can also vary across DBMS platforms.  I would suggest expanding or revising this paragraph to be more reflective of this.

**Comment by bezaye** [comment]
> On the [SQL introduction](https://datacarpentry.org/sql-ecology-lesson/00-sql-introduction/index.html) page, we note:
> 
> > There are a number of different database management systems for working with relational data. We’re going to use SQLite today, but basically everything we teach you will apply to the other database systems as well (e.g. MySQL, PostgreSQL, MS Access, MS SQL Server, Oracle Database and Filemaker Pro). The only things that will differ are the details of exactly how to import and export data and the details of data types.
> 
> This is misleading, as there are many other differences between different database systems. For example, SQLite does not do every kind of `join` (inner/outer/full/left/right). Acceptable syntax can also vary across DBMS platforms. I would suggest expanding or revising this paragraph to be more reflective of this.

@maneesha  your are right, its more than misleading but rather wrong actually.  It can be difficult to explain their difference in detail because this is an introduction lesson. Otherwise we will end up being out of scope covering distributed systems, or performance and scalability and so on. What about editing it like this instead?
************************************
There are different database management systems to work with a relational database. For example, SQLite, MySQL, Potsgresql, MSSQL Server, and many more. Each of them differ mainly based on their scalability, but they all share the same core principles of relational database. In this lesson, we use SQLite to introduce you to SQL and data retrieval from a relational database.
***********************************

**Comment by maneesha** [comment]
Agreed that  deep level description of various DBMSs is way out of scope here, but we should not have any wrong or misleading information here.  I've just made one edit to avoid a sentence fragment:


> There are different database management systems to work with relational databases such as SQLite, MySQL, Potsgresql, MSSQL Server, and many more. Each of them differ mainly based on their scalability, but they all share the same core principles of relational database. In this lesson, we use SQLite to introduce you to SQL and data retrieval from a relational database.
