### ISSUE TITLE
add a step to setup page to test all the files and software have been downloaded and installed

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [datacarpentry/sql-ecology-lesson#288]
and also add **<**(previous page, in this case it is the home page), **>**(next page, in the case it is the first lesson) to improve the usability and easy navigation like what we can see other lesson pages

Text suggest to add:

**Make sure everything is working before starting your lesson**

open DB browser  
click on "open Database" > locate the unzipped file 
you should see three tables: "plots", "species", and "surveys"
All good to go.

**Comment by ChristinaLK** [comment]
Some follow up questions for you @Wang-Jing-NZ 

- regarding the arrows - is your suggestion that we add text labels to the existing `<` and `>` arrows on each page that lead to the previous/next pages? Or something else? 

- Which part of the lesson should have the text you've suggested to make sure everything is working?

**Comment by Wang-Jing-NZ** [comment]
Re: navigation arrows:
see this page: https://datacarpentry.org/sql-ecology-lesson/00-sql-introduction/index.html, it has arrows to go back to the course home page and the next page. however, on the setup page, https://datacarpentry.org/sql-ecology-lesson/setup.html, it doesn't have navigation arrows to go to the home page or to the next page to start the lesson. The learner needs to use the "go back to" button provided by Web browser to go back to the home page and then start the lesson.

Re: where to add the text
The text is to add to the end of the this page, https://datacarpentry.org/sql-ecology-lesson/setup.html, after Section "Software" as a new section.

Hope it helps to clear what I was trying to tell.

**Comment by ChristinaLK** [comment]
That clarifies things. Thanks!

**Comment by ChristinaLK** [comment]
After reviewing the lesson, we already have fairly detailed instructions on loading up the database and/or the .csv files in the initial section; I don't want to duplicate that in the Setup, but we could add a link from Setup to that section of the lesson if people want to test their downloads. 

Because the navigation arrows would be something that apply to the general format of the lesson, that suggestion should be moved to the Carpentries "styles" repository [here](https://github.com/carpentries/styles).
