### ISSUE TITLE
Rendering and link(s) to SQL cheat sheet

### ISSUE THREAD

**Issue by jd-foster** [datacarpentry/sql-ecology-lesson#360]
The  file `sql-cheat-sheet.md` is not rendered to HTML and is not linkable within the lesson.
It is only linked at the moment under the Reference page:
https://datacarpentry.org/sql-ecology-lesson/reference.html
but may be useful to link elsewhere in the future.

@zkamvar Is there a method to render a Markdown page when it's supplementary to the lesson?

**Comment by adamancer** [comment]
If we want to render the cheat sheet as part of the lesson, I think it would make sense to integrate it into the Reference page instead of having it as a separate page. 

On the other hand, if the intention is to have a standalone file, we could also just render it ourselves (something like [this](https://github.com/datacarpentry/sql-ecology-lesson/blob/contrib/adamancer/episodes/files/sql-cheat-sheet.html).) Is there a benefit to keeping the file as markdown if it's not going to be rendered automatically?

**Comment by zkamvar** [comment]
> Is there a method to render a Markdown page when it's supplementary to the lesson?

@jd-foster, yes. Put the markdown file into the `learners/` folder and it will be available via the "More" menu. For example, I have https://carpentries.github.io/sandpaper-docs/github-pat.html in the documentation lesson, which is built from https://github.com/carpentries/sandpaper-docs/blob/main/learners/github-pat.md
