### ISSUE TITLE
Add info on ability to change data type within SQLite after data is imported

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology-lesson#37]
At the beginning we have people import the data from csv as an exercise. There's a step on import where you have to select the data type for the field. Some people select the wrong type or nothing at all and wonder what they can do to change it. 

If you right click or Control click on the column name in the Structure tab, then there's an Edit Column option and you can type in a new data type. When you go to save it, it does warn you that this is dangerous behavior, so people are being warned, but it might be nice to show this option and also to say why it's not generally a good idea to change data types.

**Comment by waveform80** [comment]
I'm surprised it warns about this. I thought the column types in that engine were merely used to hint at the conversions to be used when querying, but otherwise were [basically ignored](http://www.sqlite.org/datatype3.html)? Still, it's probably good that the warning is there given it's most certainly dangerous in the general case (i.e. in other engines).

**Comment by hlapp** [comment]
I'm all for teaching quick solutions to problems students encounter, but doing it this way is completely non-portable, and so now we're moving from using SQLite in Firefox as a teaching tool to teaching it as a tool that people would commonly carry forward using in their daily lives.

**Comment by waveform80** [comment]
I could add a section on using `ALTER TABLE`, but to be frank almost nothing about DDL is perfectly portable (especially given that the major engines can't even agree on something as simple as `VARCHAR` or `TIMESTAMP`) so if you get a data-type wrong the best advice is probably either 1) drop that table and start over, or 2) get out the manual and figure out if/how you can fix it in your particular engine of choice.

As for whether people should be using SQLite generally ... well, it may not be the quickest/best engine around but I'd still rather people used it for data than Excel ;)

**Comment by ethanwhite** [comment]
I suggest that we add this quick save trick as a tip in the, currently non-existent, instructors notes, so that instructors/helpers know how to quickly solve this issue to get students going again during the workshop. That way we don't teach it (given all of the complexities mentioned above), but folks running the workshop know about it when they need it.

**Comment by apawlik** [comment]
I agree on adding tips for instructors. At the moment I added them to the index.md (on how to zoom). I suggest maybe a separate file but link it at the index.md Otherwise, I fear, instructors are likely to miss that.

**Comment by tracykteal** [comment]
Adding instructor notes and then adding this information to those notes sounds like the best plan. I'll work on that.

**Comment by tracykteal** [comment]
Also to @waveform80 and @hlapp about using SQLite, it is a part of a discussion in https://github.com/datacarpentry/sql-ecology/issues/32

**Comment by kcranston** [comment]
I've added [instructor notes](https://github.com/datacarpentry/sql-ecology-lesson/blob/gh-pages/instructor-notes.md) and included this tip about dealing with students that select the wrong data type.
