### ISSUE TITLE
data for this lesson

### ISSUE THREAD

**Issue by njamescouk** [datacarpentry/sql-ecology-lesson#90]
I got lost at "Let’s all open the database we downloaded in SQLite Manager by clicking on the open file icon." in http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction.html

There's a reference in http://www.datacarpentry.org/sql-ecology-lesson/ to data files on figshare, I had a look but couldn't see anything.

In the Import section the figshare link to 3 csv files gives a 404.

**Comment by orchid00** [comment]
I'm not sure what the problem is but the link for the files is this: https://figshare.com/articles/Portal_Project_Teaching_Database/1314459. If you wait a little bit (a few seconds in my case) you can see at the top all the files, there you will find .csv files and .sqlite. Are you able to check again? If you tell me where will be best to put up the link I can modify the intro page.

**Comment by njamescouk** [comment]
tried the link in the introduction again and it does work. I didn't wait long enough, started reading the text expecting a download link at end of page when it was probably sitting at the top of the page.

I still find the "open the database" wording difficult. perhaps in a class that would work, but I'd expect a preamble along the lines of use sqlite manager to download database d from URL u.

I say this because in my limited experience as an sc student I found it stressful downloading things, creating accounts on websites etc etc whilst trying to absorb what I was being told and undertaking various challenges. I prefer having my ducks in a row!
